[package]
name = "example-sortable-list"
description = "Minimal sortable-list demo for taino-leptos-dnd."
version = "0.6.1"
edition = "2021"
publish = false
license.workspace = true

[dependencies]
leptos = { workspace = true, features = ["csr"] }
taino-dnd-leptos = { path = "../../crates/taino-dnd-leptos", version = "0.6.1" }
taino-dnd-core = { path = "../../crates/taino-dnd-core", version = "0.6.1" }
console_error_panic_hook = "0.1"
wasm-bindgen = { workspace = true }

[lints]
workspace = true
